version: '3.8'

services:
  message-processor:
    build:
      context: ./message-processor
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - ENV=${ENV:-dev}
    volumes:
      - ./config:/app/config
    networks:
      - prj-network

  data-api:
    build:
      context: ./data-api
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - ENV=${ENV:-dev}
    volumes:
      - ./config:/app/config
    networks:
      - prj-network

networks:
  prj-network:
    driver: bridge
